version: '3'
services:
  db:
    image: postgres
    container_name: postgres_db
    ports:
      - "5432:5432"
  app:
    build: .
    container_name: postgres_app
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
      # - /myapp/tmp/pids/
      - /myapp/tmp/cache/
    links:
      - db
    ports:
      - "3000:3000"
    depends_on:
      - db
